userInputs=list(range(5))
userInputs[0]=input('enter first value ')
userInputs[1]=input('enter second value ')
userInputs[2]=input('enter third value ')
userInputs[3]=input('enter fourth value ')
userInputs[4]=input('enter fifth value ')
print(userInputs)
userInputs.sort()
print(userInputs.sort())
print(userInputs[len(userInputs)-1])
